# Generated by Django 4.2.5 on 2023-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('gender', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=9)),
                ('phone', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
