# Generated by Django 4.2.5 on 2024-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontak',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
